### ISSUE TITLE
QWebView import trouble

### ISSUE THREAD

**Issue by tschoonj** [oasys-aps-kit/XRayServer#2]
Hi Luca,

I just set up a brand new Anaconda installation of OASYS1 with python 3.6, installed all the add-on packages, and everything appears to work except the `xrayserver` package which throws exceptions on startup:

````
Could not import 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0h'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0h.py", line 23, in <module>
    from PyQt5.QtWebKit import QWebView
ImportError: cannot import name 'QWebView'
INFO:orangecanvas.registry.discovery:Could not import 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0h'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0h.py", line 23, in <module>
    from PyQt5.QtWebKit import QWebView
ImportError: cannot import name 'QWebView'
Error while importing 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0h_OLD'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0h_OLD.py", line 3, in <module>
    raise NotImplementedError()
NotImplementedError
WARNING:orangecanvas.registry.discovery:Error while importing 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0h_OLD'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0h_OLD.py", line 3, in <module>
    raise NotImplementedError()
NotImplementedError
Could not import 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0p'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0p.py", line 21, in <module>
    from PyQt5.QtWebKit import QWebView
ImportError: cannot import name 'QWebView'
INFO:orangecanvas.registry.discovery:Could not import 'orangecontrib.xrayserver.widgets.xrayserver.ow_x0p'.
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 262, in iter_widget_descriptions
    module = asmodule(name)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/envs/oasys1/lib/python3.6/site-packages/orangecontrib/xrayserver/widgets/xrayserver/ow_x0p.py", line 21, in <module>
    from PyQt5.QtWebKit import QWebView
ImportError: cannot import name 'QWebView'
````

It would appear that QWebView has been removed from [Qt 5.6](https://wiki.qt.io/New_Features_in_Qt_5.6) and is no longer built by default. It is certainly not present in Anaconda's Qt and PyQt packages.

Best,

Tom

**Comment by lucarebuffi** [comment]
Dear Tom,

it is a more than known issue. I struggled a lot to have it fixed. The only distribution that works in Linux is Miniconda3. Please see the OASYS1 Linux installation script here: 

https://github.com/srio/oasys-installation-scripts/blob/master/Release%201.0/prepare_installation.sh

and follow these instructions:

https://github.com/srio/oasys-installation-scripts/wiki/Installing-Oasys-in-Linux-(debian-ubuntu)

**Comment by lucarebuffi** [comment]
Another remark: for this problem XRayServer stopped working properly. I have in plan to have it fixed asap.

**Comment by tschoonj** [comment]
Actually I am using Anaconda, which is just the full version of Miniconda, and with the python 3.6 interpreter provided by it.

I installed qt and pyqt with:

````
conda install qt pyqt=5
````

**Comment by lucarebuffi** [comment]
Take a look on the scripts. It strongly depends of the particular distribution. According to Linux forums, PyQt QtWebkit has some special issues during compilation and the result is a mess. I repeat, I struggled a lot on that. Which Linux distribution are you using?

**Comment by lucarebuffi** [comment]
Any way, I use this command:

$HOME/miniconda3/bin/conda install -c defaults pyqt=5 qt

**Comment by tschoonj** [comment]
Hi Luca,

I had another look at the code and it looks like a bug at your end. I could make the problem go away with a small patch. Will open a pull request in a couple of minutes.

Thanks,

Tom

**Comment by lucarebuffi** [comment]
Tom, please do not waste your time, since XrayServer is going to be totally refactored. In any case, if this patch is not time consuming for you and you want to upload it, I thank you in advance for your help.
